import type { MaterialConfig } from './types'

export const defaultMaterial: MaterialConfig = {
  preset: 'default',
  color: '#888888',
  metalness: 0,
  roughness: 0.5,
  emissive: '#000000',
  emissiveIntensity: 0,
  opacity: 1,
  transparent: false,
  wireframe: false,
  transmission: 0,
  ior: 1.5,
  thickness: 0,
  clearcoat: 0,
  clearcoatRoughness: 0,
  envMapIntensity: 1,
}

export const materialPresets: Record<string, Partial<MaterialConfig>> = {
  matteClay: {
    preset: 'matteClay',
    color: '#c4b5a0',
    metalness: 0,
    roughness: 1,
    emissive: '#000000',
    emissiveIntensity: 0,
    transmission: 0,
    clearcoat: 0,
  },
  brushedMetal: {
    preset: 'brushedMetal',
    color: '#9ca3af',
    metalness: 0.92,
    roughness: 0.28,
    emissive: '#000000',
    emissiveIntensity: 0,
    transmission: 0,
    clearcoat: 0.1,
    clearcoatRoughness: 0.3,
  },
  chrome: {
    preset: 'chrome',
    color: '#ffffff',
    metalness: 1,
    roughness: 0.03,
    emissive: '#000000',
    emissiveIntensity: 0,
    transmission: 0,
    clearcoat: 0,
    envMapIntensity: 1.5,
  },
  glass: {
    preset: 'glass',
    color: '#ffffff',
    metalness: 0,
    roughness: 0.05,
    emissive: '#000000',
    emissiveIntensity: 0,
    transparent: true,
    opacity: 0.3,
    transmission: 0.95,
    ior: 1.52,
    thickness: 0.5,
    clearcoat: 1,
    clearcoatRoughness: 0,
    envMapIntensity: 1.2,
  },
  plastic: {
    preset: 'plastic',
    color: '#ef4444',
    metalness: 0,
    roughness: 0.3,
    emissive: '#000000',
    emissiveIntensity: 0,
    transmission: 0,
    clearcoat: 0.8,
    clearcoatRoughness: 0.1,
  },
  neonEmissive: {
    preset: 'neonEmissive',
    color: '#06b6d4',
    metalness: 0,
    roughness: 0.2,
    emissive: '#06b6d4',
    emissiveIntensity: 3,
    transmission: 0,
    clearcoat: 0,
  },
  gold: {
    preset: 'gold',
    color: '#fbbf24',
    metalness: 1,
    roughness: 0.18,
    emissive: '#000000',
    emissiveIntensity: 0,
    transmission: 0,
    clearcoat: 0.3,
    clearcoatRoughness: 0.15,
    envMapIntensity: 1.3,
  },
  frostedTranslucent: {
    preset: 'frostedTranslucent',
    color: '#e0e7ff',
    metalness: 0,
    roughness: 0.6,
    emissive: '#000000',
    emissiveIntensity: 0,
    transparent: true,
    opacity: 0.5,
    transmission: 0.6,
    ior: 1.3,
    thickness: 0.8,
    clearcoat: 0,
  },
  obsidian: {
    preset: 'obsidian',
    color: '#1e1b4b',
    metalness: 0.6,
    roughness: 0.12,
    emissive: '#312e81',
    emissiveIntensity: 0.15,
    transmission: 0,
    clearcoat: 1,
    clearcoatRoughness: 0.05,
    envMapIntensity: 1.4,
  },
  copper: {
    preset: 'copper',
    color: '#d97706',
    metalness: 1,
    roughness: 0.25,
    emissive: '#000000',
    emissiveIntensity: 0,
    transmission: 0,
    clearcoat: 0.2,
    clearcoatRoughness: 0.2,
  },
  pearl: {
    preset: 'pearl',
    color: '#fdf4ff',
    metalness: 0.3,
    roughness: 0.15,
    emissive: '#fae8ff',
    emissiveIntensity: 0.1,
    transmission: 0,
    clearcoat: 1,
    clearcoatRoughness: 0.05,
    envMapIntensity: 1.2,
  },
}

export function applyPreset(preset: string): MaterialConfig {
  const p = materialPresets[preset]
  if (!p) return { ...defaultMaterial }
  return { ...defaultMaterial, ...p }
}
