import type { ScenePreset } from './types'
import { applyPreset, defaultMaterial } from './materials'

export const scenePresets: Record<string, ScenePreset> = {
  studioProduct: {
    name: 'Studio Product',
    description: 'Clean studio lighting for product visualization',
    objects: [
      {
        id: 'hero-knot',
        name: 'Hero Torus Knot',
        type: 'torusKnot',
        position: [0, 1.2, 0],
        rotation: [0.3, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('chrome'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.3,
        geometryArgs: [0.8, 0.3, 128, 32],
      },
      {
        id: 'sphere-glass',
        name: 'Glass Sphere',
        type: 'sphere',
        position: [-2.2, 0.7, 0.8],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('glass'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'float',
        animationSpeed: 0.5,
        geometryArgs: [0.7, 64, 64],
      },
      {
        id: 'icosa-gold',
        name: 'Golden Icosahedron',
        type: 'icosahedron',
        position: [2.3, 0.8, -0.5],
        rotation: [0.5, 0.3, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('gold'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.5,
        geometryArgs: [0.65, 0],
      },
      {
        id: 'dodeca-clay',
        name: 'Clay Dodecahedron',
        type: 'dodecahedron',
        position: [-1, 0.55, -2],
        rotation: [0.2, 0.5, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('matteClay'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.2,
        geometryArgs: [0.55, 0],
      },
      {
        id: 'box-obsidian',
        name: 'Obsidian Cube',
        type: 'box',
        position: [1.5, 0.45, 2],
        rotation: [0, 0.785, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('obsidian'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'float',
        animationSpeed: 0.3,
        geometryArgs: [0.9, 0.9, 0.9],
      },
      {
        id: 'torus-copper',
        name: 'Copper Ring',
        type: 'torus',
        position: [0, 2.8, -1],
        rotation: [1.2, 0.3, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('copper'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.4,
        geometryArgs: [0.6, 0.15, 32, 64],
      },
    ],
    lights: [
      {
        id: 'key',
        name: 'Key Light',
        type: 'directional',
        position: [5, 8, 3],
        color: '#ffffff',
        intensity: 2,
        castShadow: true,
        visible: true,
      },
      {
        id: 'fill',
        name: 'Fill Light',
        type: 'directional',
        position: [-4, 4, -2],
        color: '#c4d4ff',
        intensity: 0.8,
        castShadow: false,
        visible: true,
      },
      {
        id: 'rim',
        name: 'Rim Light',
        type: 'point',
        position: [-2, 3, -4],
        color: '#ffd4a8',
        intensity: 15,
        castShadow: false,
        visible: true,
        distance: 12,
        decay: 2,
      },
      {
        id: 'accent',
        name: 'Accent Spot',
        type: 'spot',
        position: [3, 5, -3],
        color: '#a78bfa',
        intensity: 30,
        castShadow: true,
        visible: true,
        angle: 0.5,
        penumbra: 0.8,
        distance: 15,
        decay: 2,
      },
    ],
    ambientIntensity: 0.15,
    ambientColor: '#c4d4ff',
    backgroundColor: '#09090b',
    environmentPreset: 'studio',
    environmentIntensity: 0.6,
    exposure: 1.1,
    toneMapping: 'ACESFilmic',
    bloomEnabled: true,
    bloomIntensity: 0.3,
    bloomThreshold: 0.85,
  },

  sciFiNeon: {
    name: 'Sci-Fi Neon',
    description: 'Dark scene with neon-lit objects and bloom',
    objects: [
      {
        id: 'neon-knot',
        name: 'Neon Torus Knot',
        type: 'torusKnot',
        position: [0, 1.5, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('neonEmissive'),
        castShadow: false,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.6,
        geometryArgs: [0.9, 0.25, 128, 32],
      },
      {
        id: 'dark-sphere',
        name: 'Dark Sphere',
        type: 'sphere',
        position: [2, 1, -1],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...applyPreset('obsidian'), emissive: '#4f46e5', emissiveIntensity: 0.5 },
        castShadow: true,
        receiveShadow: false,
        animationType: 'pulse',
        animationSpeed: 0.5,
        geometryArgs: [0.8, 64, 64],
      },
      {
        id: 'neon-ring',
        name: 'Cyan Ring',
        type: 'torus',
        position: [-2, 2, 0],
        rotation: [1.57, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...defaultMaterial, color: '#22d3ee', emissive: '#22d3ee', emissiveIntensity: 4, metalness: 0, roughness: 0.1 },
        castShadow: false,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.8,
        geometryArgs: [0.7, 0.08, 64, 32],
      },
      {
        id: 'neon-octa',
        name: 'Magenta Octahedron',
        type: 'octahedron',
        position: [0, 0.6, 2.5],
        rotation: [0, 0.5, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...defaultMaterial, color: '#e879f9', emissive: '#e879f9', emissiveIntensity: 2.5, metalness: 0.1, roughness: 0.2 },
        castShadow: false,
        receiveShadow: false,
        animationType: 'float',
        animationSpeed: 0.4,
        geometryArgs: [0.5],
      },
    ],
    lights: [
      {
        id: 'dim-key',
        name: 'Dim Key',
        type: 'directional',
        position: [3, 6, 2],
        color: '#334155',
        intensity: 0.5,
        castShadow: true,
        visible: true,
      },
      {
        id: 'blue-point',
        name: 'Blue Point',
        type: 'point',
        position: [-3, 2, 3],
        color: '#3b82f6',
        intensity: 20,
        castShadow: false,
        visible: true,
        distance: 10,
        decay: 2,
      },
      {
        id: 'magenta-spot',
        name: 'Magenta Spot',
        type: 'spot',
        position: [2, 4, -2],
        color: '#d946ef',
        intensity: 40,
        castShadow: true,
        visible: true,
        angle: 0.6,
        penumbra: 0.9,
        distance: 12,
        decay: 2,
      },
    ],
    ambientIntensity: 0.03,
    ambientColor: '#1e1b4b',
    backgroundColor: '#030712',
    environmentPreset: 'night',
    environmentIntensity: 0.15,
    exposure: 1.3,
    toneMapping: 'ACESFilmic',
    bloomEnabled: true,
    bloomIntensity: 1.2,
    bloomThreshold: 0.4,
  },

  architecturalMinimal: {
    name: 'Architectural Minimal',
    description: 'Clean, geometric forms with soft directional lighting',
    objects: [
      {
        id: 'arch-cylinder',
        name: 'Column',
        type: 'cylinder',
        position: [0, 1.5, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...applyPreset('matteClay'), color: '#e5e5e5' },
        castShadow: true,
        receiveShadow: false,
        animationType: 'none',
        animationSpeed: 0,
        geometryArgs: [0.4, 0.4, 3, 32],
      },
      {
        id: 'arch-sphere',
        name: 'Stone Sphere',
        type: 'sphere',
        position: [0, 3.3, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...applyPreset('matteClay'), color: '#d4d4d8' },
        castShadow: true,
        receiveShadow: false,
        animationType: 'none',
        animationSpeed: 0,
        geometryArgs: [0.5, 64, 64],
      },
      {
        id: 'arch-box1',
        name: 'Plinth Left',
        type: 'box',
        position: [-2.5, 0.5, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...applyPreset('matteClay'), color: '#f5f5f4' },
        castShadow: true,
        receiveShadow: true,
        animationType: 'none',
        animationSpeed: 0,
        geometryArgs: [1, 1, 1],
      },
      {
        id: 'arch-box2',
        name: 'Plinth Right',
        type: 'box',
        position: [2.5, 0.75, 0],
        rotation: [0, 0.3, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...applyPreset('matteClay'), color: '#d6d3d1' },
        castShadow: true,
        receiveShadow: true,
        animationType: 'none',
        animationSpeed: 0,
        geometryArgs: [1.2, 1.5, 0.8],
      },
      {
        id: 'arch-cone',
        name: 'Cone',
        type: 'cone',
        position: [-2.5, 1.6, 0],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('pearl'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'none',
        animationSpeed: 0,
        geometryArgs: [0.35, 0.7, 32],
      },
    ],
    lights: [
      {
        id: 'arch-key',
        name: 'Soft Key',
        type: 'directional',
        position: [6, 10, 4],
        color: '#ffffff',
        intensity: 1.5,
        castShadow: true,
        visible: true,
      },
      {
        id: 'arch-fill',
        name: 'Cool Fill',
        type: 'directional',
        position: [-5, 6, -3],
        color: '#e0e7ff',
        intensity: 0.6,
        castShadow: false,
        visible: true,
      },
    ],
    ambientIntensity: 0.4,
    ambientColor: '#f5f5f4',
    backgroundColor: '#fafaf9',
    environmentPreset: 'apartment',
    environmentIntensity: 0.4,
    exposure: 1.0,
    toneMapping: 'Neutral',
    bloomEnabled: false,
    bloomIntensity: 0,
    bloomThreshold: 1,
  },

  sunsetOutdoor: {
    name: 'Sunset Outdoor',
    description: 'Warm golden-hour lighting with long shadows',
    objects: [
      {
        id: 'sun-knot',
        name: 'Copper Knot',
        type: 'torusKnot',
        position: [0, 1.5, 0],
        rotation: [0.5, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('copper'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.2,
        geometryArgs: [0.8, 0.28, 128, 32],
      },
      {
        id: 'sun-sphere',
        name: 'Pearl Sphere',
        type: 'sphere',
        position: [2, 0.8, 1.5],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('pearl'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'float',
        animationSpeed: 0.3,
        geometryArgs: [0.6, 64, 64],
      },
      {
        id: 'sun-dodeca',
        name: 'Gold Dodecahedron',
        type: 'dodecahedron',
        position: [-1.8, 0.7, -1],
        rotation: [0.3, 0.6, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('gold'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.3,
        geometryArgs: [0.6, 0],
      },
    ],
    lights: [
      {
        id: 'sun-main',
        name: 'Sun',
        type: 'directional',
        position: [-8, 4, 2],
        color: '#ffb366',
        intensity: 3,
        castShadow: true,
        visible: true,
      },
      {
        id: 'sun-sky',
        name: 'Sky Fill',
        type: 'directional',
        position: [4, 8, -3],
        color: '#93c5fd',
        intensity: 0.4,
        castShadow: false,
        visible: true,
      },
      {
        id: 'sun-bounce',
        name: 'Ground Bounce',
        type: 'point',
        position: [0, 0.5, 0],
        color: '#fde68a',
        intensity: 5,
        castShadow: false,
        visible: true,
        distance: 8,
        decay: 2,
      },
    ],
    ambientIntensity: 0.15,
    ambientColor: '#fde68a',
    backgroundColor: '#1c1917',
    environmentPreset: 'sunset',
    environmentIntensity: 1.0,
    exposure: 1.2,
    toneMapping: 'ACESFilmic',
    bloomEnabled: true,
    bloomIntensity: 0.5,
    bloomThreshold: 0.7,
  },

  darkCinematic: {
    name: 'Dark Cinematic',
    description: 'Moody, dramatic lighting with deep shadows',
    objects: [
      {
        id: 'cin-knot',
        name: 'Obsidian Knot',
        type: 'torusKnot',
        position: [0, 1.3, 0],
        rotation: [0.2, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('obsidian'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.15,
        geometryArgs: [0.85, 0.32, 128, 32],
      },
      {
        id: 'cin-sphere',
        name: 'Chrome Sphere',
        type: 'sphere',
        position: [-2, 0.8, 1],
        rotation: [0, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('chrome'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'none',
        animationSpeed: 0,
        geometryArgs: [0.65, 64, 64],
      },
      {
        id: 'cin-box',
        name: 'Frosted Cube',
        type: 'box',
        position: [2, 0.55, -0.5],
        rotation: [0, 0.785, 0],
        scale: [1, 1, 1],
        visible: true,
        material: applyPreset('frostedTranslucent'),
        castShadow: true,
        receiveShadow: false,
        animationType: 'float',
        animationSpeed: 0.25,
        geometryArgs: [1.1, 1.1, 1.1],
      },
      {
        id: 'cin-ring',
        name: 'Emissive Ring',
        type: 'torus',
        position: [0, 3, -1.5],
        rotation: [0.8, 0, 0],
        scale: [1, 1, 1],
        visible: true,
        material: { ...defaultMaterial, color: '#dc2626', emissive: '#dc2626', emissiveIntensity: 2, metalness: 0.3, roughness: 0.1 },
        castShadow: false,
        receiveShadow: false,
        animationType: 'rotate',
        animationSpeed: 0.5,
        geometryArgs: [0.8, 0.1, 64, 32],
      },
    ],
    lights: [
      {
        id: 'cin-key',
        name: 'Hard Key',
        type: 'spot',
        position: [4, 6, 2],
        color: '#fef3c7',
        intensity: 60,
        castShadow: true,
        visible: true,
        angle: 0.4,
        penumbra: 0.6,
        distance: 20,
        decay: 2,
      },
      {
        id: 'cin-rim',
        name: 'Rim',
        type: 'point',
        position: [-3, 2, -4],
        color: '#60a5fa',
        intensity: 12,
        castShadow: false,
        visible: true,
        distance: 10,
        decay: 2,
      },
    ],
    ambientIntensity: 0.02,
    ambientColor: '#1e293b',
    backgroundColor: '#020617',
    environmentPreset: 'night',
    environmentIntensity: 0.1,
    exposure: 1.4,
    toneMapping: 'ACESFilmic',
    bloomEnabled: true,
    bloomIntensity: 0.8,
    bloomThreshold: 0.5,
  },
}
